# Generated by Django 3.1.3 on 2022-03-17 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucm_service_area_id', models.TextField()),
                ('liq_id', models.TextField(unique=True)),
                ('openet_id', models.TextField(null=True)),
                ('acres', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vw_crop_name', models.TextField(unique=True)),
                ('ucm_group', models.TextField(null=True)),
                ('liq_crop_name', models.TextField(null=True)),
                ('liq_crop_id', models.CharField(max_length=5, null=True)),
                ('liq_group_code', models.CharField(max_length=5, null=True)),
                ('liq_group_name', models.TextField(null=True)),
                ('_efficiency_options', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=4)),
                ('efficiency', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_id', models.TextField(unique=True)),
                ('apn', models.TextField()),
                ('ucm_service_area_id', models.TextField()),
                ('allocated_amount', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WellProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField(null=True)),
                ('semi_year', models.SmallIntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production', to='allocate.crop')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='allocate.well')),
            ],
        ),
        migrations.CreateModel(
            name='AgFieldResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_probability', models.DecimalField(decimal_places=5, max_digits=5)),
                ('agfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='allocate.agfield')),
                ('irrigation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_by_field', to='allocate.irrigationtype')),
            ],
        ),
        migrations.AddField(
            model_name='agfield',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='allocate.crop'),
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=4, max_digits=16)),
                ('variable_name', models.TextField(null=True)),
                ('allocation', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('agfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipes', to='allocate.agfield')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipes', to='allocate.well')),
            ],
            options={
                'unique_together': {('well', 'agfield')},
            },
        ),
        migrations.CreateModel(
            name='CropIrrigationTypePrior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.DecimalField(decimal_places=5, max_digits=5)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_priors', to='allocate.crop')),
                ('irrigation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_priors', to='allocate.irrigationtype')),
            ],
            options={
                'unique_together': {('crop', 'irrigation_type')},
            },
        ),
        migrations.CreateModel(
            name='AgFieldTimestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestep', models.SmallIntegerField()),
                ('consumptive_use', models.DecimalField(decimal_places=4, max_digits=16)),
                ('precip', models.DecimalField(decimal_places=4, max_digits=16)),
                ('agfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesteps', to='allocate.agfield')),
            ],
            options={
                'unique_together': {('agfield', 'timestep')},
            },
        ),
    ]
