# Generated by Django 3.1.3 on 2022-03-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropirrigationtypeprior',
            name='probability',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
