# Generated by Django 3.2.7 on 2021-11-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellproduction',
            name='month',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wellproduction',
            name='semi_year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
