# Generated by Django 3.2.7 on 2021-11-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0002_auto_20211118_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='allocation',
            field=models.DecimalField(decimal_places=4, max_digits=16, null=True),
        ),
    ]
