# Generated by Django 3.1.3 on 2022-03-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0002_auto_20220317_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationtype',
            old_name='code',
            new_name='type_code',
        ),
    ]
