# Generated by Django 3.1.3 on 2022-03-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0003_auto_20220318_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='production_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Metered'), (2, 'Unmetered Worksheet')], default=1),
        ),
    ]
