# Generated by Django 3.2.7 on 2022-03-09 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0004_agfield_acres'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('efficiency', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='AgFieldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_probability', models.DecimalField(decimal_places=5, max_digits=5)),
                ('agfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='allocate.agfield')),
                ('irrigation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_by_field', to='allocate.irrigationtype')),
            ],
        ),
        migrations.CreateModel(
            name='CropIrrigationTypePrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.DecimalField(decimal_places=5, max_digits=5)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_priors', to='allocate.crop')),
                ('irrigation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_priors', to='allocate.irrigationtype')),
            ],
            options={
                'unique_together': {('crop', 'irrigation_type')},
            },
        ),
    ]
