# Generated by Django 3.2.7 on 2022-03-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0005_agfieldresult_cropirrigationtypeprior_irrigationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agfield',
            name='crop',
        ),
        migrations.AddField(
            model_name='agfield',
            name='crop',
            field=models.ManyToManyField(null=True, to='allocate.Crop'),
        ),
    ]
